#!/usr/bin/python3

import os

# Symbols to use for the different battery statuses
BATTERY_STATUS_SYMBOLS = {
    "Charging": "↑",
    "Discharging": "↓",
    "Full": "🔋"
}

# `acpi -b` returns a complex string that we'll need to parse
battery_output = os.popen('acpi -b').read()
# There's only one battery, so ignore this label
battery_output = battery_output.lstrip("Battery 0: ")

try:
    # The output has these for components:
    #   1. The status, e.g. "Discharging"
    #   2. The percentage full
    #   3. A "message", which can be a display of the time remaining for whatever
    #      operation the status entails (discharging or charging), depending on the
    #      rate
    battery_status, battery_percent, battery_message = battery_output.split(", ", maxsplit=3)[:3]
except ValueError:
    # If the battery is full, then there will be no message
    battery_status, battery_percent = battery_output.split(", ", maxsplit=2)[:2]

# Default to no symbol in the case of an unknown status
status_symbol = BATTERY_STATUS_SYMBOLS.get(battery_status, "")

# Remove the '%' from the end of the percent readout
battery_percent = battery_percent.rstrip().rstrip('%')

print(f"{status_symbol}{battery_percent}")
