#!/usr/bin/python3

import os
import typing
import re

VOLUME_ENABLED = {
    "[on]": "🔊",
    "[off]": "🔇"
}

# `amixer sget Master` returns a complex string that we'll need to parse
volume_output = os.popen('amixer sget Master').read()
volume_output_lines = volume_output.strip().split("\n")


def extract_channel_info(channel_status: str) -> typing.Tuple[str, str]:
    status_components = channel_status.split()

    return (
        # Extract the volume percentage
        re.match("\[(\d{2,3})%\]", status_components[4]).group(1),
        # Turn the "enabled" component into a bool
        VOLUME_ENABLED.get(status_components[5], "🔔")
    )

left_channel, right_channel = map(
    lambda channel: extract_channel_info(channel.strip()),
   volume_output_lines[5:7]
)

# If the channels are unbalanced, display appropriately
if left_channel != right_channel:
    print("channels unbalanced")
else:
    print(f"{left_channel[1]}{left_channel[0]}")
